server:
  servlet:
    context-path: /api/v1
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://rm-2ze61i7u6d7a3fwp9yo.mysql.rds.aliyuncs.com/jpetstore?&serverTimezone=GMT&useSSL=true


    username: team
    password: Aaa5225975
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
